# Generated by Django 3.1 on 2020-08-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('formula', models.CharField(max_length=50)),
                ('molecular_weight', models.FloatField(max_length=10)),
                ('mw_units', models.CharField(max_length=10)),
            ],
        ),
    ]
