# Generated by Django 3.1 on 2020-08-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0003_auto_20200812_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='elements',
            field=models.ManyToManyField(blank=True, to='compounds.Element'),
        ),
    ]
